# Tomcat
server:
  port: 8080
spring:
# database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/ssm_crud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  # jpa  
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format-sql: true    
    show-sql: true
      
  # springMVC  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
